version: "3.8"

services:

  auth-db:
    image: mysql:8
    container_name: auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - auth_data:/var/lib/mysql

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: auth_db
      JWT_SECRET: mysecret

  student-service:
    build: ./student-service
    container_name: student-service
    ports:
      - "5002:5002"
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: student_db

  course-service:
    build: ./course-service
    container_name: course-service
    ports:
      - "5003:5003"
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: course_db

  teacher-service:
    build: ./teacher-service
    container_name: teacher-service
    ports:
      - "5004:5004"
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: teacher_db

  admin-service:
    build: ./admin-service
    container_name: admin-service
    ports:
      - "5005:5005"
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: admin_db

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - student-service
      - course-service
      - teacher-service
      - admin-service

volumes:
  auth_data:
